In [1]:
#Machine learning - Regression analysis using Pytorch
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
#Sample data
X = torch.tensor([1,2,3,4,5], dtype = torch.float32).view(-1,1)
y = 2*X+1 # Linear relationship

In [3]:
X

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])

In [4]:
# Define linear regression model
class LinearRegressionModel(nn.Module):
  def __init__(self, input_size, output_size):
    super(LinearRegressionModel, self).__init__()
    self.linear = nn.Linear(input_size, output_size)

  def forward(self, X):
    return self.linear(X)

In [5]:
# Instantiate the model, loss function, and optimizer
input_size = 1  # In this case, there is only one feature (X)
output_size = 1  # Output size is one (y)
model = LinearRegressionModel(input_size, output_size)
criterion = nn.MSELoss()  # Mean Squared Error loss
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Stochastic Gradient Descent

In [6]:
#Training loop
num_epochs = 1000
for epoch in range(num_epochs):
  #forward pass
  outputs = model(X)
  #calculate the loss
  loss = criterion(outputs, y.view(-1,1))

  #backward pass and optimization
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

In [7]:
#print the loss every 100 epochs
if(epoch + 1) % 100 == 0:
  print(f'Epoch [{epoch+1}/{num_epochs}], Loss:{loss.item():.4f}')

Epoch [1000/1000], Loss:0.0000


In [8]:
# Test the model
with torch.no_grad():
    test_data = torch.tensor([6, 7, 8], dtype=torch.float32).view(-1, 1)
    predictions = model(test_data)
    print(f'Predictions: {predictions.flatten().numpy()}')

Predictions: [13.007766 15.011016 17.014267]


In [9]:
#Tutorial 2
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [10]:
import pandas as pd
import os

In [11]:
os.path.expanduser('~')

'/root'

In [12]:
bg = pd.read_csv('/content/drive/MyDrive/temp_data.csv')

In [13]:
#Import data from csv to pandas DataFrame
bg.head()

temp  atemp
0  11.9    8.9
1  12.0    9.3
2  13.4   10.7
3  14.8   12.1
4  15.8   13.1

In [14]:
X_pandas = bg['temp']
y_pandas = bg['atemp']

In [15]:
#conver to tensors
data_x = X_pandas.head(100).values
data_y = y_pandas.head(100).values
X = torch.tensor(data_x, dtype = torch.float32).reshape(-1,1)
y = torch.tensor(data_y, dtype = torch.float32).reshape(-1,1)

In [16]:
model = nn.Linear(1,1)
loss_fn = nn.MSELoss() #Mean Square Error
optimizer = optim.SGD(model.parameters(), lr = 0.01)

In [23]:
# Train the model
n_epochs = 40  # Number of epochs to run

for epoch in range(n_epochs):
    # Forward pass
    y_pred = model(X)

    # Compute loss
    loss = loss_fn(y_pred, y)

    # Backward pass
    loss.backward()

    # Update parameters
    optimizer.step()

    # Zero gradients
    optimizer.zero_grad()

    # Print loss
    print(f'Epoch: {epoch+1}, Loss: {loss.item():.4f}')


Epoch: 1, Loss: 275.4850
Epoch: 2, Loss: 3308.2275
Epoch: 3, Loss: 39821.5391
Epoch: 4, Loss: 479430.7500
Epoch: 5, Loss: 5772186.0000
Epoch: 6, Loss: 69495352.0000
Epoch: 7, Loss: 836702720.0000
Epoch: 8, Loss: 10073643008.0000
Epoch: 9, Loss: 121283649536.0000
Epoch: 10, Loss: 1460217708544.0000
Epoch: 11, Loss: 17580572016640.0000
Epoch: 12, Loss: 211664628613120.0000
Epoch: 13, Loss: 2548377774456832.0000
Epoch: 14, Loss: 30681676552077312.0000
Epoch: 15, Loss: 369398248659484672.0000
Epoch: 16, Loss: 4447442620737650688.0000
Epoch: 17, Loss: 53545851234830778368.0000
Epoch: 18, Loss: 644675579590553370624.0000
Epoch: 19, Loss: 7761702319143870529536.0000
Epoch: 20, Loss: 93448521332034675671040.0000
Epoch: 21, Loss: 1125091420637518448558080.0000
Epoch: 22, Loss: 13545755462131167600312320.0000
Epoch: 23, Loss: 163086742018462460359475200.0000
Epoch: 24, Loss: 1963515416243516397578092544.0000
Epoch: 25, Loss: 23640138279046546721890893824.0000
Epoch: 26, Loss: 2846200691265684850

In [24]:
#Display the predicted values
predicted = model(X).detach().numpy()
display(predicted)

array([[-5.4215134e+22],
       [-5.4668228e+22],
       [-6.1011539e+22],
       [-6.7354854e+22],
       [-7.1885791e+22],
       [-7.5510544e+22],
       [-7.5963638e+22],
       [-7.6869816e+22],
       [-7.6869816e+22],
       [-7.6869816e+22],
       [-7.5057446e+22],
       [-7.1432697e+22],
       [-6.9620322e+22],
       [-6.8261042e+22],
       [-6.8261042e+22],
       [-6.7807943e+22],
       [-6.6448667e+22],
       [-6.4636288e+22],
       [-6.4636288e+22],
       [-6.3730105e+22],
       [-6.1464632e+22],
       [-5.8746070e+22],
       [-5.6933696e+22],
       [-5.6480602e+22],
       [-5.8292977e+22],
       [-6.5089386e+22],
       [-7.0979603e+22],
       [-7.5057446e+22],
       [-7.7322914e+22],
       [-7.9588387e+22],
       [-8.0494575e+22],
       [-8.0494575e+22],
       [-8.0947664e+22],
       [-7.9588387e+22],
       [-7.6869816e+22],
       [-7.0979603e+22],
       [-6.3730105e+22],
       [-5.5574415e+22],
       [-5.0137291e+22],
       [-4.8324917e+22],


In [26]:
#porblem - increase in loss with each epoch
model = nn.Linear(1,1)
loss_fn = nn.MSELoss() #Mean Square Error
optimizer = optim.SGD(model.parameters(), lr = 0.005)

In [27]:
# Train the model
n_epochs = 40  # Number of epochs to run

for epoch in range(n_epochs):
    # Forward pass
    y_pred = model(X)

    # Compute loss
    loss = loss_fn(y_pred, y)

    # Backward pass
    loss.backward()

    # Update parameters
    optimizer.step()

    # Zero gradients
    optimizer.zero_grad()

    # Print loss
    print(f'Epoch: {epoch+1}, Loss: {loss.item():.4f}')

Epoch: 1, Loss: 570.2732
Epoch: 2, Loss: 869.2245
Epoch: 3, Loss: 1325.1288
Epoch: 4, Loss: 2020.3862
Epoch: 5, Loss: 3080.6663
Epoch: 6, Loss: 4697.6030
Epoch: 7, Loss: 7163.4424
Epoch: 8, Loss: 10923.8779
Epoch: 9, Loss: 16658.6113
Epoch: 10, Loss: 25404.1152
Epoch: 11, Loss: 38741.0781
Epoch: 12, Loss: 59080.1094
Epoch: 13, Loss: 90097.3281
Epoch: 14, Loss: 137398.7812
Epoch: 15, Loss: 209534.0000
Epoch: 16, Loss: 319541.5938
Epoch: 17, Loss: 487303.8125
Epoch: 18, Loss: 743142.6250
Epoch: 19, Loss: 1133301.5000
Epoch: 20, Loss: 1728295.3750
Epoch: 21, Loss: 2635666.7500
Epoch: 22, Loss: 4019419.7500
Epoch: 23, Loss: 6129657.5000
Epoch: 24, Loss: 9347791.0000
Epoch: 25, Loss: 14255478.0000
Epoch: 26, Loss: 21739736.0000
Epoch: 27, Loss: 33153350.0000
Epoch: 28, Loss: 50559172.0000
Epoch: 29, Loss: 77103224.0000
Epoch: 30, Loss: 117583208.0000
Epoch: 31, Loss: 179315696.0000
Epoch: 32, Loss: 273458272.0000
Epoch: 33, Loss: 417026656.0000
Epoch: 34, Loss: 635969920.0000
Epoch: 35, Los

In [28]:
#This issue may be avoided by scalling without changing the lr
data_x = data_x/data_x.max()
data_y = data_y

In [29]:
#convert to tensors
# data_x = X_pandas.head(100).values
# data_y = y_pandas.head(100).values

X = torch.tensor(data_x, dtype = torch.float32).reshape(-1,1)
y = torch.tensor(data_y, dtype = torch.float32).reshape(-1,1)

In [30]:
#create the model
model = nn.Linear(1,1)
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.01)

#train the model
n_epochs = 40
for epoch in range(n_epochs):
  y_pred = model(X)
  loss = loss_fn(y_pred, y)
  loss.backward()
  optimizer.step()
  optimizer.zero_grad()
  print(f'epoch: {epoch + 1}, loss = {loss.item():.4f}')

epoch: 1, loss = 169.1282
epoch: 2, loss = 159.8260
epoch: 3, loss = 151.0552
epoch: 4, loss = 142.7855
epoch: 5, loss = 134.9883
epoch: 6, loss = 127.6364
epoch: 7, loss = 120.7046
epoch: 8, loss = 114.1687
epoch: 9, loss = 108.0062
epoch: 10, loss = 102.1957
epoch: 11, loss = 96.7170
epoch: 12, loss = 91.5513
epoch: 13, loss = 86.6806
epoch: 14, loss = 82.0881
epoch: 15, loss = 77.7579
epoch: 16, loss = 73.6750
epoch: 17, loss = 69.8252
epoch: 18, loss = 66.1953
epoch: 19, loss = 62.7726
epoch: 20, loss = 59.5454
epoch: 21, loss = 56.5024
epoch: 22, loss = 53.6331
epoch: 23, loss = 50.9276
epoch: 24, loss = 48.3766
epoch: 25, loss = 45.9711
epoch: 26, loss = 43.7030
epoch: 27, loss = 41.5643
epoch: 28, loss = 39.5476
epoch: 29, loss = 37.6460
epoch: 30, loss = 35.8529
epoch: 31, loss = 34.1621
epoch: 32, loss = 32.5677
epoch: 33, loss = 31.0643
epoch: 34, loss = 29.6466
epoch: 35, loss = 28.3097
epoch: 36, loss = 27.0491
epoch: 37, loss = 25.8603
epoch: 38, loss = 24.7393
epoch: 39, 

In [31]:
predicted = model(X).detach().numpy()
display(predicted)

array([[ 8.695105 ],
       [ 8.71628  ],
       [ 9.012735 ],
       [ 9.309191 ],
       [ 9.520945 ],
       [ 9.690348 ],
       [ 9.711523 ],
       [ 9.753874 ],
       [ 9.753874 ],
       [ 9.753874 ],
       [ 9.669172 ],
       [ 9.499769 ],
       [ 9.415068 ],
       [ 9.3515415],
       [ 9.3515415],
       [ 9.330366 ],
       [ 9.26684  ],
       [ 9.182138 ],
       [ 9.182138 ],
       [ 9.139788 ],
       [ 9.033911 ],
       [ 8.906858 ],
       [ 8.822157 ],
       [ 8.8009815],
       [ 8.885683 ],
       [ 9.203314 ],
       [ 9.478594 ],
       [ 9.669172 ],
       [ 9.775049 ],
       [ 9.880926 ],
       [ 9.923277 ],
       [ 9.923277 ],
       [ 9.944452 ],
       [ 9.880926 ],
       [ 9.753874 ],
       [ 9.478594 ],
       [ 9.139788 ],
       [ 8.758631 ],
       [ 8.504526 ],
       [ 8.419825 ],
       [ 8.419825 ],
       [ 8.441    ],
       [ 8.483351 ],
       [ 8.419825 ],
       [ 8.356298 ],
       [ 8.165721 ],
       [ 8.017493 ],
       [ 7.82